// <auto-generated />
using System;
using AspNetCore.MVC.Sample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCore.MVC.Sample.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("AspNetCore.MVC.Sample.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Building");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new { Id = 1, Building = 1, Street = "New Orchard Road" },
                        new { Id = 2, Building = 17, Street = "One Microsoft Way" },
                        new { Id = 3, Building = 1600, Street = "Amphitheatre Parkway" }
                    );
                });

            modelBuilder.Entity("AspNetCore.MVC.Sample.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Offices");

                    b.HasData(
                        new { Id = 1, AddressId = 1, Name = "New Orchard Road" },
                        new { Id = 2, AddressId = 2, Name = "One Microsoft Way" },
                        new { Id = 3, AddressId = 3, Name = "Amphitheatre Parkway" }
                    );
                });

            modelBuilder.Entity("AspNetCore.MVC.Sample.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Extn");

                    b.Property<string>("Name");

                    b.Property<int>("OfficeId");

                    b.Property<string>("Position");

                    b.Property<decimal>("Salary");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Persons");

                    b.HasData(
                        new { Id = 1, Extn = 5421, Name = "Tiger Nixon", OfficeId = 1, Position = "System Architect", Salary = 320800m, StartDate = new DateTime(2011, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 2, Extn = 8422, Name = "Garrett Winters", OfficeId = 1, Position = "Accountant", Salary = 170750m, StartDate = new DateTime(2011, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 3, Extn = 1562, Name = "Ashton Cox", OfficeId = 2, Position = "Junior Technical Author", Salary = 86000m, StartDate = new DateTime(2009, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 4, Extn = 6224, Name = "Cedric Kelly", OfficeId = 1, Position = "Senior Javascript Developer", Salary = 433060m, StartDate = new DateTime(2012, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 5, Extn = 5407, Name = "Airi Satou", OfficeId = 1, Position = "Accountant", Salary = 162700m, StartDate = new DateTime(2008, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 6, Extn = 4804, Name = "Brielle Williamson", OfficeId = 1, Position = "Integration Specialist", Salary = 372000m, StartDate = new DateTime(2012, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 7, Extn = 9608, Name = "Herrod Chandler", OfficeId = 1, Position = "Sales Assistant", Salary = 137500m, StartDate = new DateTime(2012, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 8, Extn = 6200, Name = "Rhona Davidson", OfficeId = 1, Position = "Integration Specialist", Salary = 327900m, StartDate = new DateTime(2010, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 9, Extn = 2360, Name = "Colleen Hurst", OfficeId = 2, Position = "Javascript Developer", Salary = 205500m, StartDate = new DateTime(2009, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 10, Extn = 1667, Name = "Sonya Frost", OfficeId = 2, Position = "Software Engineer", Salary = 103600m, StartDate = new DateTime(2008, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 11, Extn = 3814, Name = "Jena Gaines", OfficeId = 1, Position = "Office Manager", Salary = 90560m, StartDate = new DateTime(2008, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 12, Extn = 9497, Name = "Quinn Flynn", OfficeId = 2, Position = "Support Lead", Salary = 342000m, StartDate = new DateTime(2013, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 13, Extn = 6741, Name = "Charde Marshall", OfficeId = 2, Position = "Regional Director", Salary = 470600m, StartDate = new DateTime(2008, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 14, Extn = 3597, Name = "Haley Kennedy", OfficeId = 1, Position = "Senior Marketing Designer", Salary = 313500m, StartDate = new DateTime(2012, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 15, Extn = 1965, Name = "Tatyana Fitzpatrick", OfficeId = 1, Position = "Regional Director", Salary = 385750m, StartDate = new DateTime(2010, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 16, Extn = 1581, Name = "Michael Silva", OfficeId = 3, Position = "Marketing Designer", Salary = 198500m, StartDate = new DateTime(2012, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 17, Extn = 3059, Name = "Paul Byrd", OfficeId = 1, Position = "Chief Financial Officer (CFO)", Salary = 725000m, StartDate = new DateTime(2010, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 18, Extn = 1721, Name = "Gloria Little", OfficeId = 3, Position = "Systems Administrator", Salary = 237500m, StartDate = new DateTime(2009, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 19, Extn = 2558, Name = "Bradley Greer", OfficeId = 1, Position = "Software Engineer", Salary = 132000m, StartDate = new DateTime(2012, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 20, Extn = 2290, Name = "Dai Rios", OfficeId = 1, Position = "Personnel Lead", Salary = 217500m, StartDate = new DateTime(2012, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 21, Extn = 1937, Name = "Jenette Caldwell", OfficeId = 1, Position = "Development Lead", Salary = 345000m, StartDate = new DateTime(2011, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 22, Extn = 6154, Name = "Yuri Berry", OfficeId = 3, Position = "Chief Marketing Officer (CMO)", Salary = 675000m, StartDate = new DateTime(2009, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 23, Extn = 8330, Name = "Caesar Vance", OfficeId = 1, Position = "Pre-Sales Support", Salary = 106450m, StartDate = new DateTime(2011, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 24, Extn = 3023, Name = "Doris Wilder", OfficeId = 1, Position = "Sales Assistant", Salary = 85600m, StartDate = new DateTime(2010, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 25, Extn = 5797, Name = "Angelica Ramos", OfficeId = 1, Position = "Chief Executive Officer (CEO)", Salary = 1200000m, StartDate = new DateTime(2009, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 26, Extn = 8822, Name = "Gavin Joyce", OfficeId = 1, Position = "Developer", Salary = 92575m, StartDate = new DateTime(2010, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 27, Extn = 9239, Name = "Jennifer Chang", OfficeId = 3, Position = "Regional Director", Salary = 357650m, StartDate = new DateTime(2010, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 28, Extn = 1314, Name = "Brenden Wagner", OfficeId = 1, Position = "Software Engineer", Salary = 206850m, StartDate = new DateTime(2011, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 29, Extn = 2947, Name = "Fiona Green", OfficeId = 1, Position = "Chief Operating Officer (COO)", Salary = 850000m, StartDate = new DateTime(2010, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 30, Extn = 8899, Name = "Shou Itou", OfficeId = 2, Position = "Regional Marketing", Salary = 163000m, StartDate = new DateTime(2011, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 31, Extn = 2769, Name = "Michelle House", OfficeId = 1, Position = "Integration Specialist", Salary = 95400m, StartDate = new DateTime(2011, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 32, Extn = 6832, Name = "Suki Burks", OfficeId = 1, Position = "Developer", Salary = 114500m, StartDate = new DateTime(2009, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 33, Extn = 3606, Name = "Prescott Bartlett", OfficeId = 2, Position = "Technical Author", Salary = 145000m, StartDate = new DateTime(2011, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 34, Extn = 2860, Name = "Gavin Cortez", OfficeId = 1, Position = "Team Leader", Salary = 235500m, StartDate = new DateTime(2008, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 35, Extn = 8240, Name = "Martena Mccray", OfficeId = 2, Position = "Post-Sales support", Salary = 324050m, StartDate = new DateTime(2011, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 36, Extn = 5384, Name = "Unity Butler", OfficeId = 1, Position = "Marketing Designer", Salary = 85675m, StartDate = new DateTime(2009, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 37, Extn = 7031, Name = "Howard Hatfield", OfficeId = 3, Position = "Office Manager", Salary = 164500m, StartDate = new DateTime(2008, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 38, Extn = 6318, Name = "Hope Fuentes", OfficeId = 1, Position = "Secretary", Salary = 109850m, StartDate = new DateTime(2010, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 39, Extn = 9422, Name = "Vivian Harrell", OfficeId = 1, Position = "Financial Controller", Salary = 452500m, StartDate = new DateTime(2009, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 40, Extn = 7580, Name = "Timothy Mooney", OfficeId = 1, Position = "Office Manager", Salary = 136200m, StartDate = new DateTime(2008, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 41, Extn = 1042, Name = "Jackson Bradshaw", OfficeId = 1, Position = "Director", Salary = 645750m, StartDate = new DateTime(2008, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 42, Extn = 2120, Name = "Olivia Liang", OfficeId = 3, Position = "Support Engineer", Salary = 234500m, StartDate = new DateTime(2011, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 43, Extn = 6222, Name = "Bruno Nash", OfficeId = 1, Position = "Software Engineer", Salary = 163500m, StartDate = new DateTime(2011, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 44, Extn = 9383, Name = "Sakura Yamamoto", OfficeId = 2, Position = "Support Engineer", Salary = 139575m, StartDate = new DateTime(2009, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 45, Extn = 8327, Name = "Thor Walton", OfficeId = 1, Position = "Developer", Salary = 98540m, StartDate = new DateTime(2013, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 46, Extn = 2927, Name = "Finn Camacho", OfficeId = 1, Position = "Support Engineer", Salary = 87500m, StartDate = new DateTime(2009, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 47, Extn = 8352, Name = "Serge Baldwin", OfficeId = 1, Position = "Data Coordinator", Salary = 138575m, StartDate = new DateTime(2012, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 48, Extn = 7439, Name = "Zenaida Frank", OfficeId = 1, Position = "Software Engineer", Salary = 125250m, StartDate = new DateTime(2010, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 49, Extn = 4389, Name = "Zorita Serrano", OfficeId = 1, Position = "Software Engineer", Salary = 115000m, StartDate = new DateTime(2012, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 50, Extn = 3431, Name = "Jennifer Acosta", OfficeId = 1, Position = "Junior Javascript Developer", Salary = 75650m, StartDate = new DateTime(2013, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 51, Extn = 3990, Name = "Cara Stevens", OfficeId = 1, Position = "Sales Assistant", Salary = 145600m, StartDate = new DateTime(2011, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 52, Extn = 1016, Name = "Hermione Butler", OfficeId = 1, Position = "Regional Director", Salary = 356250m, StartDate = new DateTime(2011, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 53, Extn = 6733, Name = "Lael Greer", OfficeId = 2, Position = "Systems Administrator", Salary = 103500m, StartDate = new DateTime(2009, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 54, Extn = 8196, Name = "Jonas Alexander", OfficeId = 2, Position = "Developer", Salary = 86500m, StartDate = new DateTime(2010, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 55, Extn = 6373, Name = "Shad Decker", OfficeId = 1, Position = "Regional Director", Salary = 183000m, StartDate = new DateTime(2008, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 56, Extn = 5384, Name = "Michael Bruce", OfficeId = 1, Position = "Javascript Developer", Salary = 183000m, StartDate = new DateTime(2011, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 57, Extn = 4226, Name = "Donna Snider", OfficeId = 1, Position = "Customer Support", Salary = 112000m, StartDate = new DateTime(2011, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                    );
                });

            modelBuilder.Entity("AspNetCore.MVC.Sample.Models.Office", b =>
                {
                    b.HasOne("AspNetCore.MVC.Sample.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspNetCore.MVC.Sample.Models.Person", b =>
                {
                    b.HasOne("AspNetCore.MVC.Sample.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
